name: Slither Analysis
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SAST_Scanning:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Slither
      uses: crytic/slither-action@v0.1.1
      continue-on-error: true 
      with:
        sarif: results.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
        
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
          name: sast_slither_output 
          path: results.sarif #commentss
